#!/usr/bin/env sh
# Snap maintainence launcher

if ! test -e "${SNAP_USER_COMMON}/xnsw.exe"; then
    printf -- \
        'Application executable not found, downloading from the official website...\n'
    cd "${SNAP_USER_COMMON}"
    if test "$(
            curl \
                --location \
                --remote-name \
                --remote-header-name \
                --write-out '%{http_code}' \
                --silent \
                --show-error \
                http://www.xnotestopwatch.com/xnsw.exe
        )" != 200; then
        printf -- \
            'Error: Unable to download the application executable from the official website.\n' \
            1>&2
        exit 1
    fi
    cd - >/dev/null
fi

exec "${@}"
