#!/usr/bin/env bash
# Snap maintainence launcher
set -eu

maintainer_notice_read_marker_file="${SNAP_USER_COMMON}/skip-maintainer-notice.marker"
if ! test -e "${maintainer_notice_read_marker_file}"; then
msg_text="$(cat <<EOF
Hello, this is 林博仁(Buo-ren Lin), the maintainer of the XNote Stopwatch snap.

I would like to inform you that this is NOT an official distribution of the
XNote Stopwatch application, please report all issues regarding the usage of
this snap to the snap's own issue tracker:

    Issues · brlin-tw/xnote-stopwatch-snap
    https://github.com/brlin-tw/xnote-stopwatch-snap/issues

Thank you.

This dialog will only display once, to see it again remove the
<tt>${maintainer_notice_read_marker_file}</tt>
marker file and relaunch the application.
EOF
)"
    zenity_opts=(
        --title='Notice from the snap maintainer'
        --width=640
        --info
        --ok-label='Continue'
        --text="${msg_text}"
    )
    if ! zenity "${zenity_opts[@]}"; then
        printf \
            'Error: Unable to present the snap maintainer notice.\n.' \
            1>&2
        exit 2
    fi
    if ! touch "${maintainer_notice_read_marker_file}"; then
        printf \
            'Error: Unable to create the maintainer notice read marker file.\n' \
            1>&2
        exit 2
    fi
fi

security_confinement_warning_marker_file="${SNAP_USER_COMMON}/skip-security-confinement-warning.marker"
if ! test -e "${security_confinement_warning_marker_file}"; then
msg_text="$(cat <<EOF
Due to the licensing restrictions, this application is not bundled in the snap
and will be downloaded from the official website in runtime.

There is a potential risk that the downloaded software may be replaced by a
malware if an evil actor has hijacked the website.  As an attempt to mitigate
this risk the snap is by default not connected to the <tt>home</tt> snapd
security confinement interface, which allows the application to access your
files in your home directory.

If you have specific needs that require the snap to connect to the <tt>home</tt>
interface(e.g. play custom audio alarm file), you may do so by running the
following command in a text terminal:

    sudo snap connect ${SNAP_NAME}:home

Thank you.

This dialog will only display once, to see it again remove the
<tt>${security_confinement_warning_marker_file}</tt>
marker file and relaunch the application.
EOF
)"
    zenity_opts=(
        --width=640
        --title='Security confinement warning - The home interface'
        --info
        --ok-label='Continue'
        --text="${msg_text}"
    )
    if ! zenity "${zenity_opts[@]}"; then
        printf \
            'Error: Unable to present the security confinement warning(home).\n.' \
            1>&2
        exit 2
    fi

    if ! touch "${security_confinement_warning_marker_file}"; then
        printf \
            'Error: Unable to create the security confinement warning read marker file.\n' \
            1>&2
        exit 2
    fi
fi

if ! test -e "${SNAP_USER_COMMON}/xnsw.exe"; then
    printf -- \
        'Application executable not found, downloading from the official website...\n'
    cd "${SNAP_USER_COMMON}"
    curl_opts=(
        --location
        --remote-name
        --remote-header-name
        --write-out '%{http_code}'
        --silent
        --show-error
    )
    if test "$(
            curl "${curl_opts[@]}" \
                http://www.xnotestopwatch.com/xnsw.exe
        )" != 200; then
        zenity_opts=(
            --title='Launcher error'
            --width=640
            --error
            --text='Unable to download the application executable from the official website.'
        )
        if ! zenity "${zenity_opts[@]}"; then
            printf \
                'Error: Unable to present the zenity error dialog.\n.' \
                1>&2
            exit 2
        fi
        exit 2
    fi
    cd - >/dev/null
fi

exec "${@}"
