name: xnote-stopwatch
base: core22
version: '1.68'
title: XNote Stopwatch (UNOFFICIAL)
summary: A multifunctional digital stopwatch/countdown timer/clock software
description: |
  XNote Stopwatch is a versatile and flexible multifunctional digital stopwatch
  / countdown timer / clock software for PC. Helpful for timekeepers at sport
  competitions, time tracking of work, or even as a metronome.

  The key features are:

  - Digital display like handheld stopwatches and clocks. But unlike those
    XNote Stopwatch can be resized to achieve any dimensions of digits: from
    fullscreen on a LCD TV (jumbotron) for public presentations like a
    'stopclock', to tiny icon on your desktop as a reminder. Along with size,
    you can adjust colors, font, transparency, etc…
  - Stopwatch mode and countdown timer mode: When the timer gets to zero, it
    can sound a warning signal, play an audio file, run an application, and
    even command external devices!
  - Customization of displayed time: You can eliminate hours, minutes, and/or
    decimals, pad leading values with zeroes, customize decimals to represent
    10, 100 or 1000 of second, 24, 25, 60 TV frames and so on. These changes
    are lossless and can be carried out at any moment.
  - Ability to capture the time at any moment (split time feature). The
    interval from a previous recorded time is calculated (lap time feature).
    You may add a comment to each noted time. Finally, the whole list of
    results can be copied through the clipboard for further processing.
  - Ability to set a custom time. This means that you can rewind the
    stopwatch backward or forward. All displaced results will be deleted.
  - Multiple stopwatches and timers with their own settings and run
    independently of each other.
  - External control through serial COM (RS-232) port: You can start,
    stop, reset the stopwatch, and snap the time with a simple on/off
    switch, photocell, and even an RFID-tag reader for accurate timekeeping!
  - Changing colors and playing warning signals when Timer is almost done.

  Despite the variety of features, XNote Stopwatch has a small memory size,
  low system resource requirements, and fast execution speed!

  **Snap-specific notes**

  * Due to differences between the WINE compatibility layer and the native
    Windows runtime, some aforementioned features may not be available
  * Due to the confined nature of snaps, some features may not be available
    or be limited
  * This is NOT an official distribution of XNote Stopwatch, please report
    any problems to the snap's own issue tracker, thank you
  * Upstream: http://www.xnotestopwatch.com/
  * Packaging source: https://github.com/Lin-Buo-Ren/xnote-stopwatch-snap

icon: snap/gui/logo.gif.64px.png
grade: stable
confinement: strict
architectures:
  - build-on: amd64
license: Proprietary

parts:
  # The sommelier script helps you snap Windows applications using Wine. It
  # initializes and configures Wine and installs the Windows application.
  sommelier:
    plugin: make
    source: https://github.com/snapcrafters/sommelier-core.git
    # WORKAROUND: The 1.0 branch isn't buildable on core22
    # https://github.com/snapcrafters/sommelier-core/issues/48
    source-branch: master
    build-packages:
      - libc6-dev-i386
      - gcc-multilib
    stage-packages:
      - xdg-user-dirs

  launchers:
    plugin: dump
    source: snap/local/launchers
    organize:
      '*-launch': bin/
    stage-packages:
      - curl

apps:
  xnote-stopwatch:
    extensions:
      - gnome
    command: bin/sommelier run-exe
    command-chain:
      - bin/xnote-stopwatch-launch
    environment:
      WINEDLLOVERRIDES: "$WINEDLLOVERRIDES;mscoree,mshtml="    # Prevent pop-ups about Wine Mono and Wine Gecko
      SOMMELIER_STRICT: "1"                                    # Make Sommelier exit when unset variable is used. (useful to find bugs in sommelier)
      RUN_EXE: '${SNAP_USER_COMMON}/xnsw.exe'

  # The wine command can be used to run applications inside the wine
  # environment that this snap uses.
  #
  # For example, users can configure the wine environment of this snap
  # by running `myapp.wine winecfg`.
  wine:
    extensions:
      - gnome
    command: bin/sommelier

  # The winetricks command can be used to run winetricks inside the wine
  # environment that this snap uses.
  winetricks:
    extensions:
      - gnome
    command: bin/sommelier winetricks

plugs:
  # Regular file access
  home:
  removable-media:

  # For download the application
  network:

  # For wineserver functionality
  network-bind:

  # Graphical resources access
  desktop:
  desktop-legacy:
  x11:
  unity7:
  wayland:

  # Playing notification sound
  audio-playback:

  # WINE runtime
  wine-runtime-c22:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime-core22
  wine-9-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-9-stable-core22
